version: "3"

vars:
  APP_NAME: "preview-env"
  IMAGE: "c8n.io/aminehmida/preview-env:latest"
  PORT: 3000
  DOMAIN: "prod.previewenv.aminehmida.com"

tasks:
  compile:
    desc: "Compile kubernetes manifests using Jsonnet to manifests/"
    cmds:
      - jsonnet -S --ext-str appName="{{.APP_NAME}}" --ext-str image="{{.IMAGE}}" --ext-str port="{{.PORT}}" --ext-str domain="{{.DOMAIN}}" main.jsonnet -m manifests/
  apply:
    desc: "Apply kubernetes manifests"
    deps: [compile]
    cmds:
      - kubectl --kubeconfig=../tmp/kubeconfig apply -f manifests/
  delete:
    desc: "Delete kubernetes manifests"
    cmds:
      - kubectl --kubeconfig=../tmp/kubeconfig delete -f manifests/
  clean:
    desc: "Clean up generated manifests"
    cmds:
      - rm -rf manifests/*